EXPERIMENT_NAME = "aug_seed44_no_scheduler"

BATCH_SIZE = 128
LEARNING_RATE = 1e-3
NUM_EPOCHS = 40
NUM_CLASSES = 10
SPLIT_SEED = 42  # Keep fixed across all runs
SEED = 44       # Training seed: 42, 43, or 44

USE_AUGMENTATION = True
WEIGHT_DECAY = 0.0

USE_LR_SCHEDULER = False
LR_SCHEDULER_MODE = "min"
LR_SCHEDULER_FACTOR = 0.5
LR_SCHEDULER_PATIENCE = 3
MIN_LR = 1e-5